[velox]
build_args = [
  '-trimpath',
  '-ldflags',
  '-s -X github.com/roadrunner-server/roadrunner/v2025/internal/meta.version=v2025.1.3 -X github.com/roadrunner-server/roadrunner/v2025/internal/meta.buildTime=${TIME}',
]

[roadrunner]
ref = "v2025.1.3"

[github]
[github.token]
token = "${RT_TOKEN}"

[github.plugins]
logger = { ref = "v5.1.9", owner = "roadrunner-server", repository = "logger" }
http = { ref = "v5.2.8", owner = "roadrunner-server", repository = "http" }
server = { ref = "v5.2.10", owner = "roadrunner-server", repository = "server" }

[debug]
enabled = false

[log]
level = "info"
mode = "production"
