version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/apps/go-hello"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/python-hello"
    schedule:
      interval: "weekly"
