pre-push:
  parallel: true

pre-commit:
  commands:
    phpstan:
      run: just phpstan

    fmt:
      run: just fmt

    lint:
      run: just lint

    phpcs-fix:
      run: just phpcs-fix

    fmt-justfile:
      run: just fmt
