# include:
  # - compose.rpc.yml

services:
  apps:
    image: laravel_app_dev:1.0
    container_name: apps_dev
    env_file:
      - dev.env
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./apps:/app
    command: sh run.sh
    networks:
      - app_dev
    depends_on:
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  caddy:
    image: docker.io/library/caddy:latest
    container_name: caddy_dev
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./apps:/app
    networks:
      - app_dev
    depends_on:
      - apps
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 128M

  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: buggregator_dev
    networks:
      - app_dev
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: docker.io/library/redis:latest
    container_name: redis_dev
    env_file:
      - dev-frontend.env
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      memlock: -1

  minio:
    image: docker.io/minio/minio:latest
    container_name: minio_dev
    command: [
      "server",
      "--console-address",
      ":9001",
      "/data"
    ]
    env_file:
      - dev.env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

volumes:
  redis_data:
    name: redis_dev_data
  minio_data:
    name: minio_dev_data

networks:
  app_dev:
    driver: bridge
    name: app_dev
