FROM docker.io/library/node:23-alpine3.21

RUN apk --update --no-cache add bash=5.2.37-r0 curl=8.12.1-r1

RUN curl -fsSL https://bun.sh/install | bash

ENV HOME=/root
ENV BUN_INSTALL="$HOME/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

RUN npm -g install npm-check-updates

WORKDIR /app/frontend