FROM docker.io/library/node:24-alpine3.22

RUN apk --update --no-cache add bash curl

RUN curl -fsSL https://bun.sh/install | bash

ENV HOME=/root
ENV BUN_INSTALL="$HOME/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

RUN bun install --global npm-check-updates

WORKDIR /app/frontend
