include:
  - docker-compose.yml

services:
  temboard-ui:
    image: dalibo/temboard:8
    container_name: temboard_ui_dev
    env_file:
      - temboard.env
    ports:
      - "8888:8888"
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 128M

  temboard_pgsql:
    image: postgres:16-alpine
    container_name: temboard_pgsql_dev
    env_file:
      - temboard.env
    command: [
      postgres,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=temboard_pgsql,
    ]
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  temboard-agent:
    image: dalibo/temboard-agent:8
    container_name: temboard_agent_dev
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - pgsql_run:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_dev
    links:
      - pgsql:pgsql.acme.tld
    env_file:
      - dev.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 128M
