version: '3'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor_dev
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - app_dev
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
     - 9080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 128M
