version: '3'

services:
  goridge-hello:
    image: goridge-hello:1.0
    container_name: goridge_hello_dev
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 64M
