version: '3'

tasks:
  build:
    cmds:
      - docker build --tag laravel_app_dev:1.0 .

  install:
    cmds:
      - docker exec -it apps_dev bash -c 'composer install && php artisan telescope:install && bun install'
      - docker exec -it apps_dev php artisan key:generate
      - docker exec -it apps_dev php artisan migrate

  up:
    cmds:
      - docker compose up -d

  up-with-temboard:
    cmds:
      - docker compose -f docker-compose.temboard.yml up

  queue-listen:
    cmds:
      - docker exec -it apps_dev php artisan queue:listen -vvv

  down:
    cmds:
      - docker compose down

  fix-perms:
    cmds:
      - chmod -R 777 apps/frontend/storage

  bun-dev:
    cmds:
      - docker exec -it apps_dev bun run dev

  bun-build:
    cmds:
      - docker exec -it apps_dev bun run build

  lang-update:
    cmds:
      - docker exec -it apps_dev php artisan lang:update

  phpcs-fix:
    cmds:
      - docker exec -it apps_dev vendor/bin/php-cs-fixer fix --config phpcs.php

  phpstan:
    cmds:
      - docker exec -it apps_dev ./vendor/bin/phpstan analyse --memory-limit=256M

  check-security:
    cmds:
      - docker exec -it apps_dev vendor/bin/security-checker security:check composer.lock
      - docker exec -it apps_dev composer audit

  gen-explain-queries:
    cmds:
      - docker exec -it apps_dev app:gen-explain-queries 2 json

  stats:
    cmds:
      - docker stats --no-stream

  logs:
    cmds:
      - docker compose logs -f

  bash:
    cmds:
      - docker exec -it apps_dev bash
