version: '3'

tasks:
  build:
    cmds:
      - docker buildx build --force-rm --load --tag laravel_app_dev:1.0 .
      - docker image prune -f

  install:
    cmds:
      - docker exec -it apps_dev sh -c 'composer install && php artisan horizon:publish && php artisan telescope:publish'
      - docker exec -it apps_dev php artisan key:generate
      - docker exec -it apps_dev php artisan migrate

  up:
    cmds:
      - docker compose up -d

  queue:
    cmds:
      - docker exec -it apps_dev php artisan horizon

  down:
    cmds:
      - docker compose down

  bun-install:
    cmds:
      - cd apps/frontend && bun install

  bun-dev:
    cmds:
      - cd apps/frontend && bun run dev
    env:
      HMR_HOST: localhost

  bun-prod:
    cmds:
      - cd apps/frontend && bun run build

  lang-update:
    cmds:
      - docker exec -it apps_dev php artisan lang:update

  fix-phpcs:
    cmds:
      - docker exec -it apps_dev vendor/bin/php-cs-fixer fix --config phpcs.php

  fix-perms:
    cmds:
      - chmod -R 777 apps/frontend/storage

  phpstan:
    cmds:
      - docker exec -it apps_dev ./vendor/bin/phpstan analyse --memory-limit=256M

  check-security:
    cmds:
      - docker exec -it apps_dev security-checker security:check composer.lock
      - docker exec -it apps_dev composer audit

  logs:
    cmds:
      - docker compose logs -f

  console:
    cmds:
      - docker exec -it apps_dev sh
