version: '3'

tasks:
  build:
    cmds:
      - docker build --tag go_hello:1.0 .

  lint-dockerfile:
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile

  lint-yaml:
    cmds:
      - yamllint -d relaxed taskfile.yml
