version: '3'

services:
  go-hello:
    image: go-hello:1.0
    container_name: go_hello_prod
    networks:
      - app_prod
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 64M
