version: '3'

tasks:
  certs-init:
    cmds:
      - docker run --rm -v ./certs:/certs -it cockroachdb/cockroach:v23.1.13 cert create-ca --certs-dir=/certs --ca-key=/certs/ca.key
      - docker run --rm -v ./certs:/certs -it cockroachdb/cockroach:v23.1.13 cert create-client root --certs-dir=/certs --ca-key=/certs/ca.key

  build-amd64:
    cmds:
      - cp -r ../apps .
      - cp -r ./rr/rr apps/frontend
      - docker buildx build --force-rm --load --build-arg CADDY_ARCH=amd64 --tag laravel_app_prod:1.0 .
      - docker image prune -f
      - rm -rf ./apps

  build-prune:
    cmds:
      - docker buildx prune -f

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  migrate:
    cmds:
      - docker exec -it apps_prod php artisan migrate

  console:
    cmds:
      - docker exec -it apps_prod sh

  logs:
    cmds:
      - docker compose logs -f
