version: '3'

tasks:
  build:
    cmds:
      - cp -r ../apps .
      - cp -r ./rr/rr apps/frontend
      - docker build --force-rm --load --build-arg CADDY_ARCH=amd64 --tag laravel_app_prod:1.0 .
      - docker image prune -f
      - rm -rf ./apps

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  migrate:
    cmds:
      - docker exec -it apps_prod php artisan migrate

  console:
    cmds:
      - docker exec -it apps_prod sh

  logs:
    cmds:
      - docker compose logs -f

  lint-dockerfile:
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile

  validate-and-format-caddyfile:
    cmds:
      - docker run --rm -v .:/code -i caddy:2.8-alpine caddy validate --config /code/Caddyfile
      - docker run --rm -v .:/code -i caddy:2.8-alpine caddy fmt --overwrite /code/Caddyfile
