version: '3'

tasks:
  build:
    cmds:
      - cp -r ../apps .
      - cp -r ./rr/rr apps/frontend
      - docker buildx build --force-rm --load --build-arg CADDY_ARCH=amd64 --tag laravel_app_prod:1.0 .
      - docker image prune -f
      - rm -rf ./apps

  prune-builds:
    cmds:
      - docker buildx prune -f

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  migrate:
    cmds:
      - docker exec -it apps_prod php artisan migrate

  console:
    cmds:
      - docker exec -it apps_prod sh

  logs:
    cmds:
      - docker compose logs -f
