name: "Build Go locally"

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-go:
    name: build go

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: extractions/setup-just@v3

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Install packages
        run: sudo apt-get install -y libzmq3-dev

      - name: Build
        run: |
          cd apps/go-hello
          just build-local

      - name: Check app
        run: |
          file ./apps/go-hello/go_hello
