name: "Build dev container"

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-dev:
    name: build dev

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: gacts/install-podman@v1

      - uses: extractions/setup-just@v3

      - name: Check podman version
        run: podman --version

      - name: Build apps/frontend for development
        run: just build
