name: build-prod

on:
  workflow_dispatch:

jobs:
  build-prod:
    name: build prod

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: gacts/install-podman@v1

      - uses: extractions/setup-just@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Check podman version
        run: podman --version

      - name: Build RoadRunner
        run: |
          cd prod/rr
          sh download.sh
          RT_TOKEN=${GITHUB_TOKEN} sh build.sh
          just build

      - name: Build apps/frontend for production
        run: |
          cd prod
          just build
