name: check and test code

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./apps/frontend

jobs:
  check-and-test:
    name: check and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, zip, curl, gd, bcmath, exif, fileinfo, intl, json, mysqli, pdo_mysql, soap, sqlite3
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction
          composer global require enlightn/security-checker

      - name: Set up key and migrate database
        run: |
          cp -n ../../dev-frontend.env .env
          php artisan key:generate
          php artisan migrate --force

      - name: Check code
        run: sh check-code.sh

      - name: Run tests
        run: php artisan test

      - name: Check security
        run: |
          security-checker security:check composer.lock
          composer audit
