name: check and test code

on:
  workflow_dispatch:

jobs:
  check-and-test:
    name: check and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: gacts/install-podman@v1

      - name: Install dependencies
        run: |
          sudo apt-get install -y qemu-system-x86
          curl -s https://api.github.com/repos/containers/gvisor-tap-vsock/releases/latest | awk 'BEGIN { FS = "\"\\s*:\\s*" } /browser_download_url/ && /linux-amd64/ {print $2}' | xargs wget -O gvproxy-linux-amd64
          chmod +x ./gvproxy-linux-amd64
          sudo mkdir -p /usr/local/lib/podman/
          sudo mv gvproxy-linux-amd64 /usr/local/lib/podman/gvproxy

      - uses: extractions/setup-just@v3

      - name: Check podman version
        run: podman --version

      - name: Init podman machine
        run: podman machine init --cpus 1 --memory 2048 --disk-size 10

      - name: Start podman machine
        run: sudo podman machine start

      - name: Run containers
        run: just up

      - name: Check code
        run: just check-code

      - name: Run tests
        run: just test

      - name: Check security
        run: just check-security

      - name: Stop containers
        run: just down
