name: Dependency Audit

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual triggering

defaults:
  run:
    shell: bash
    working-directory: ./apps/frontend

jobs:
  audit:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Convert Bun lockfile to Yarn
        run: bun bun.lockb > yarn.lock

      - name: Run audit
        continue-on-error: true
        run: yarn audit --json > security-audit.json

      - name: Generate report
        continue-on-error: true
        run: |
          wget -O "npm-audit-to-report_0.2.0_linux_amd64.tar.gz" "https://github.com/egorsmkv/npm-audit-to-report/releases/download/v0.2.0/npm-audit-to-report_0.2.0_linux_amd64.tar.gz"
          tar xf npm-audit-to-report_0.2.0_linux_amd64.tar.gz
          chmod +x ./npm-audit-to-report
          ./npm-audit-to-report --fail-if-no-vulnerabilities --audit-file security-audit.json --output-file report.md

      - name: Create issue if problems found
        uses: peter-evans/create-issue-from-file@v5
        if: ${{ success() }}
        with:
          title: Weekly Dependency Audit
          content-filepath: ./report.md
          labels: maintenance, dependencies
