name: Dependency Audit

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual triggering

defaults:
  run:
    shell: bash
    working-directory: ./apps/frontend

jobs:
  audit:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Convert Bun lockfile to Yarn
        run: bun bun.lockb > yarn.lock

      - name: Run audit
        continue-on-error: true
        run: yarn audit --json > security-audit.json

      - name: Generate report
        continue-on-error: true
        run: |
          wget -O "audit-to-report" "https://github.com/RustedBytes/npm-audit-to-report/releases/download/v0.4.1/npm-audit-to-report"
          chmod +x ./audit-to-report
          ./audit-to-report --fail-if-no-vulnerabilities --audit-file security-audit.json --output-file report.md

      - name: Check files
        run: |
          pwd
          ls -lh

      - name: Create issue if problems found
        uses: peter-evans/create-issue-from-file@v6
        if: ${{ success() }}
        with:
          title: Weekly Dependency Audit
          content-filepath: /home/runner/work/laravel-boilerplate/laravel-boilerplate/apps/frontend/report.md
          labels: maintenance, dependencies
